title: Site
sections:
  pages:
    type: pages
    headline: Pages
    status: all
  navigation:
    type: fields
    headline: Site Navigation
    fields:
      logo:
        label: Site Logo
        type: files
        multiple: false
        template: image
        required: true
  social:
    type: fields
    headline: Social Media Links
    fields:
      linkedin:
        label: LinkedIn
        type: url
      twitter:
        label: Twitter
        type: url
      instagram:
        label: Instagram
